name: Build a docker image and push it to a repo

on:
  workflow_call:
    inputs:
      aws_region:
        required: true
        type: string
        default: us-east-1
      ecr_repository_name:
        required: true
        type: string
    secrets:
      ecr_push_role:
        required: true
    outputs:
      image:
        description: "The full ARN of the image that was created and pushed to the ECR repo"
        value: ${{ jobs.docker-build.outputs.image }}

permissions:
  id-token: write   # This is required by AWS for requesting the JWT
  contents: read    # This is required by AWS for actions/checkout

jobs:
  docker-build:
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.build-image.outputs.image }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Download Maven target directory
        uses: actions/download-artifact@v4
        with:
          name: target-dir
          path: target/
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ inputs.aws_region }}
          role-to-assume: ${{ secrets.ecr_push_role }}
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      - name: Get short Git SHA
        id: short-git-sha
        run: echo "SHORT_GIT_SHA=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV
      - name: Build, tag, and push docker image to Amazon ECR
        id: build-image
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: ${{ inputs.ecr_repository_name }}
          BRANCH: ${{ github.ref_name }}
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$SHORT_GIT_SHA -t $REGISTRY/$REPOSITORY:$BRANCH -t $REGISTRY/$REPOSITORY:latest .
          docker push $REGISTRY/$REPOSITORY:$SHORT_GIT_SHA
          docker push $REGISTRY/$REPOSITORY:$BRANCH
          docker push $REGISTRY/$REPOSITORY:latest
          echo "image=$REGISTRY/$REPOSITORY:$SHORT_GIT_SHA" >> $GITHUB_OUTPUT