name: Maven Release

on:
  workflow_call:
    inputs:
      dryRun:
        description: "Should the maven release plugin do a dry run"
        type: boolean
        required: true
        default: true
      releaseVersion:
        description: "The release version for the artifact"
        type: string
        required: true
        default: "A.B.C"
      developmentVersion:
        description: "The new development version for the artifact"
        type: string
        required: true
        default: "A.B.C-SNAPSHOT"

jobs:
  maven-release:
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          server-id: 'github'
      - name: Setup Git User
        run: |
          git config user.name "LTS Bot"
          git config user.email "lts-devs@virginia.edu"
      - name: Release
        run: mvn --batch-mode clean release:prepare release:perform -DdryRun=${{inputs.dryRun}} -DreleaseVersion=${{inputs.releaseVersion}} -DdevelopmentVersion=${{inputs.developmentVersion}}
        env:
          GITHUB_TOKEN: ${{secrets.DEPLOY_GITHUB_TOKEN}}

